### 【問題1】行列積を手計算する
以下のような行列A,Bを考えます。  

$$
    % "boldsymbol"で太字にしている
    \boldsymbol{A} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {c|cc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{c}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9 \\
        \end{array}\right] \quad
    \boldsymbol{B} =
        \left[\begin{array}{c}
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right] \quad
$$

AとBの行列積を手計算で解いてください。  
計算過程もマークダウンテキストを用いて説明してください。

### 【解答】
$$
\boldsymbol{A*B} =
        \left[\begin{array}{c}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

行列積を求める場合、n行m列成分は、「左の行列のn行目」と「右の行列のm列目」の内積から求めることができる。
例えば、左上にくる$[0][0]$だと、
$C[0][0] = A[0][0] * B[0][0] + A[0][1] * B[1][0] + A[0][2] * B[2][0]$
となる。
同様に、n行m列の求めたい箇所を計算することで行列積を求めることができる。
$C[0][1] = A[0][0] * B[0][1] + A[0][1] * B[1][1] + A[0][2] * B[2][1]$
$C[0][2] = A[0][0] * B[0][2] + A[0][1] * B[1][2] + A[0][2] * B[2][2]$
$C[1][0] = A[1][0] * B[0][0] + A[1][1] * B[1][0] + A[1][2] * B[2][0]$
$C[1][1] = A[1][0] * B[0][1] + A[1][1] * B[1][1] + A[1][2] * B[2][1]$
$C[1][2] = A[1][0] * B[0][2] + A[1][1] * B[1][2] + A[1][2] * B[2][2]$
$C[2][0] = A[2][0] * B[0][0] + A[2][1] * B[1][0] + A[2][2] * B[2][0]$
$C[2][1] = A[2][0] * B[0][1] + A[2][1] * B[1][1] + A[2][2] * B[2][1]$
$C[2][2] = A[2][0] * B[0][2] + A[2][1] * B[1][2] + A[2][2] * B[2][2]$

### 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

#### 【解答】
$$
\boldsymbol{A*B} =
        \left[\begin{array}{c}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

In [2]:
import numpy as np

a = np.array([[-1,2,3],
                       [4,-5,6],
                       [7,8,-9]])

b = np.array([[0,2,1],
                         [0,2,-8],
                         [2,9,-1]])

print(np.matmul(a, b))
print(np.dot(a, b))
print(a @ b)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 【問題3】ある要素の計算を実装
$$
\sum _{{k=1}}^{3}a_{{0,k}}b_{{k,0}}
$$

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [3]:
import numpy as np

a = np.array([[-1,2,3],
                       [4,-5,6],
                       [7,8,-9]])

b = np.array([[0,2,1],
                         [0,2,-8],
                         [2,9,-1]])

c = np.zeros((3,3)) # forで追加する為の空配列を作成

for i in range(3):
    c[0][0] = a[0][i] * b[i][0]

print(c)

[[6. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。
$$
c_{{i,j}}=\sum _{{k=1}}^{3}a_{{i,k}}b_{{k,j}}
$$

In [11]:
import numpy as np

def matrix_product(a, b, n):
    c = np.zeros((n,n)) # forで追加する為の空配列を作成（emptyだと欠損値）
    
    for i in range(n):
        for j in range(n):
            for k in range(n):
                c[i][j] += a[i][k] * b[k][j]
                
    return c

a = np.array([[-1,2,3],
                       [4,-5,6],
                       [7,8,-9]])

b = np.array([[0,2,1],
                         [0,2,-8],
                         [2,9,-1]])

n = len(a) # n × n配列の指定（配列aの長さ（行数）を取得）

c = matrix_product(a, b, n)

print(c)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


### 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [31]:
import numpy as np

d = np.array([[-1, 2, 3],
                        [4, -5, 6]])

e = np.array([[-9, 8, 7],
                        [6, -5, 4]])

d_shape_row = d.shape[1] # dの列数
e_shape_line = e.shape[0] # eの行数

if d_shape_row == e_shape_line:
    print(np.dot(d, e))
else:
    print("行列サイズが違い、計算できません。")

行列サイズが違い、計算できません。


In [22]:
"""
import numpy as np

def matrix_product(d, e, n):
    f = np.zeros((n,n)) # forで追加する為の空配列を作成（emptyだと欠損値）
    
    for i in range(n):
        for j in range(n):
            for k in range(n):
                f[i][j] += d[i][k] * e[k][j]
                
    return f

d = np.array([[-1, 2, 3],
                        [4, -5, 6]])

e = np.array([[-9, 8, 7],
                        [6, -5, 4]])

d_shape_row = d.shape[1] # dの列数
e_shape_line = e.shape[0] # eの行数

if d_shape_row == e_shape_line:
    n = len(d) # n × n配列の指定（配列aの長さ（行数）を取得）
    f = matrix_product(d, e, n)
    print(f)
else:
    print("行列サイズが違い、計算できません。")

行列サイズが違い、計算できません。


### 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [38]:
import numpy as np

d = np.array([[-1, 2, 3],
                        [4, -5, 6]])

e = np.array([[-9, 8, 7],
                        [6, -5, 4]])

d_shape_row = d.shape[1] # dの列数
e_shape_line = e.shape[0] # eの行数

if d_shape_row == e_shape_line:
    print("行列積は{}".format(np.dot(d, e)))
else:
    print("行列サイズが違い、計算できません。")
    e_T = e.T # 転置
    print("転置後の行列eは{}".format(e_T))
    print("転置後の行列積は{}".format(np.dot(d, e_T)))

行列サイズが違い、計算できません。
転置後の行列eは[[-9  6]
 [ 8 -5]
 [ 7  4]]
転置後の行列積は[[ 46  -4]
 [-34  73]]


In [41]:
import numpy as np

d = np.array([[-1, 2, 3],
                        [4, -5, 6]])

e = np.array([[-9, 8, 7],
                        [6, -5, 4]])

d_shape_row = d.shape[1] # dの列数
e_shape_line = e.shape[0] # eの行数

if d_shape_row == e_shape_line:
    print("行列積は{}".format(np.dot(d, e)))
else:
    print("行列サイズが違い、計算できません。")
    e_T = np.transpose(e) # 転置
    print("転置後の行列eは{}".format(e_T))
    print("転置後の行列積は{}".format(np.dot(d, e_T)))

行列サイズが違い、計算できません。
転置後の行列eは[[-9  6]
 [ 8 -5]
 [ 7  4]]
転置後の行列積は[[ 46  -4]
 [-34  73]]


In [45]:
"""
import numpy as np

def matrix_product(d, e, n):
    f = np.zeros((n,n)) # forで追加する為の空配列を作成（emptyだと欠損値）
    
    for i in range(n):
        for j in range(n):
            for k in range(n):
                f[i][j] += d[i][k] * e[k][j]
                
    return f

d = np.array([[-1, 2, 3],
                        [4, -5, 6]])

e = np.array([[-9, 8, 7],
                        [6, -5, 4]])

d_shape_row = d.shape[1] # dの列数
e_shape_line = e.shape[0] # eの行数

if d_shape_row == e_shape_line:
    n = len(d) # n × n配列の指定（配列dの長さ（行数）を取得）
    f = matrix_product(d, e, n)
    print(f)
else:
    print("行列サイズが違い、計算できません。")
    print("転置を行い、再計算実施。")
    e = e.T
    n = len(d) # n × n配列の指定（配列dの長さ（行数）を取得）
    f = matrix_product(d, e, n)
    print(f)

行列サイズが違い、計算できません。
転置を行い、再計算実施。
[[ 25. -16.]
 [-76.  49.]]
